storage:
  files:
    - path: /opt/file1
      filesystem: root
      contents:
        inline: Hello, world!
      mode: 0644
      user:
        id: 500
      group:
        id: 501
systemd:
  units:
    - name: jenkins.service
      enabled: true
      contents: |
        [Unit]
        Description=Jenkins master

        [Service]
        Type=oneshot
        ExecStart=/usr/bin/docker run \
                                     --name %p \
                                     -p 8080:8080 \
                                     -p 50000:50000 \
                                     jenkins/jenkins
        [Install]
        WantedBy=multi-user.target
    - name: gerrit.service
      enabled: true
      contents: |
        [Unit]
        Description=Gerrit master

        [Service]
        Type=oneshot
        ExecStart=/usr/bin/docker run \
                                     --name %p \
                                     -p 29418:29418 \
                                     -p 8081:8080 \
                                     -e CANONICAL_WEB_URL=http://localhost \
                                     gerritcodereview/gerrit

        [Install]
        WantedBy=multi-user.target
    - name: ldap.service
      enabled: true
      contents: |
        [Unit]
        Description=Ldap

        [Service]
        Type=oneshot
        ExecStart=/usr/bin/docker run \
                                     --name %p \
                                     -p 389:389 \
                                     -p 636:636 \
                                     -e LDAP_ADMIN_PASSWORD=admin \
                                     osixia/openldap
        [Install]
        WantedBy=multi-user.target
    - name: ldap-admin.service
      enabled: true
      contents: |
        [Unit]
        Description=Ldap Admin

        [Service]
        Type=oneshot
        ExecStart=/usr/bin/docker run \
                                     --name %p \
                                     -p 6443:443 \
                                     -e PHPLDAPADMIN_LDAP_HOSTS=ldap \
                                     osixia/phpldapadmin

        [Install]
        WantedBy=multi-user.target