passwd:
  users:
    - name: core
      ssh_authorized_keys:
        - key1
      home_dir: /home/user1
      groups:
        - wheel
      shell: /bin/bash
storage:
  files:
    - path: /opt/file1
      filesystem: root
      contents:
        inline: Hello, world!
      mode: 0644
      user:
        id: 500
      group:
        id: 501
systemd:
  units:
    - name: jenkins.service
      enabled: true
      contents: |
        [Unit]
        Description=Jenkins master

        [Service]
        Type=oneshot
        ExecStart=/usr/bin/echo "Hello, World!"

        [Install]
        WantedBy=multi-user.target
    - name: gerrit.service
      enabled: true
      contents: |
        [Unit]
        Description=Gerrit master

        [Service]
        Type=oneshot
        ExecStart=/usr/bin/echo "Hello, World!"

        [Install]
        WantedBy=multi-user.target
    - name: ldap.service
      enabled: true
      contents: |
        [Unit]
        Description=Ldap

        [Service]
        Type=oneshot
        ExecStart=/usr/bin/echo "Hello, World!"

        [Install]
        WantedBy=multi-user.target
    - name: ldap-admin.service
      enabled: true
      contents: |
        [Unit]
        Description=Ldap Admin

        [Service]
        Type=oneshot
        ExecStart=/usr/bin/echo "Hello, World!"

        [Install]
        WantedBy=multi-user.target